[build]
  publish = "dist"
  command = "rm -rf dist && npm install --legacy-peer-deps && chmod +x ./patches/apply-patches.sh && chmod +x ./scripts/fix-images.sh && chmod +x ./scripts/generate-case-studies.sh && ./patches/apply-patches.sh && npm run build-force && ./scripts/fix-images.sh"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  framework = "vite"

# Netlify Forms settings
# Ensure forms are forwarded to correct email
[forms]
  # Contact form settings
  [forms.contact]
    name = "contact"
    # Forms will be sent to this email address
    [forms.contact.recipients]
      email = "pascal@ingeniousdigital.com"
      # Send a copy to the support email if needed
      # email = "support@ingeniousdigital.com"
  
  # Enhanced contact form settings
  [forms.contact-enhanced]
    name = "contact-enhanced"
    [forms.contact-enhanced.recipients]
      email = "pascal@ingeniousdigital.com"
  
  # Light contact form settings
  [forms.contact-light]
    name = "contact-light"
    [forms.contact-light.recipients]
      email = "pascal@ingeniousdigital.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.googletagmanager.com 'unsafe-inline' blob:; style-src 'self' 'unsafe-inline'; font-src 'self' data: https://cdn.jsdelivr.net; img-src 'self' data: https://www.google-analytics.com https://images.unsplash.com; connect-src 'self' https://www.google-analytics.com https://cdn.jsdelivr.net; worker-src 'self' blob:; frame-src 'none'; media-src 'self'; object-src 'none'; form-action 'self'; upgrade-insecure-requests;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "accelerometer=(), autoplay=(), camera=(), cross-origin-isolated=(), display-capture=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Cache-Control = "public, max-age=31536000, must-revalidate"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"